name: flutter_branch_io
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.0

dependencies:
  deep_link_repository:
    path: packages/deep_link_repository
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
